include:
   - path:
        - ./services/volumes.yaml
        - ./services/web.yaml
        - ./services/critical.yaml
        - ./services/databases.yaml
        - ./services/external.yaml
        - ./services/authentification.yaml
        - ./services/security.yaml
        - ./services/applications.yaml
        - ./services/background-services.yaml

services: {}
