version: '3.9'

services:
  app:
    image: ghcr.io/gabe565/castsponsorskip
    environment:
    # Set the container timezone
    # See identifier list at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      TZ: UTC
    restart: always
    networks:
      bond0:
        ipv4_address: 192.168.2.219

# Define br0 network
networks:
  bond0:
    external: true
