api:
   dashboard: true
   debug: false

log:
   level: info

accessLog:
   filePath: '/var/log/traefik/access.log'
   bufferingSize: 100

global:
   checkNewVersion: true
   sendAnonymousUsage: false

entrypoints:
   http:
      address: ':80'
      forwardedHeaders:
         trustedIPs:
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 108.162.192.0/18
            - 131.0.72.0/22
            - 141.101.64.0/18
            - 162.158.0.0/15
            - 172.18.0.0/16
            - 173.245.48.0/20
            - 188.114.96.0/20
            - 190.93.240.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
      http:
         redirections:
            entryPoint:
               to: https
               scheme: https

   https:
      address: ':443'
      http:
         middlewares:
            - crowdsec-bouncer@file
            - my-traefik-real-ip@file

serversTransport:
   insecureSkipVerify: true

certificatesResolvers:
   cloudflare:
      acme:
         email: broxmodz@gmail.com
         storage: acme.json
         dnsChallenge:
            provider: cloudflare
            delayBeforeCheck: 0
            resolvers:
               - '1.1.1.1:53'
               - '1.0.0.1:53'

providers:
   docker:
      endpoint: 'unix:///var/run/docker.sock'
      exposedByDefault: false
   file:
      filename: /dynamic_conf.yml
      watch: true

experimental:
   plugins:
      traefik-real-ip:
         moduleName: 'github.com/soulbalz/traefik-real-ip'
         version: 'v1.0.3'
