version: '3.8'

volumes:
   db-data:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /opt/komodo/dbdata
   db-config:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /opt/komodo/dbconfig
   komodo-repos:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /opt/komodo/repos
   komodo-stacks:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: /opt/komodo/stacks

services:
   komodo:
      image: ghcr.io/mbecker20/komodo:latest
      container_name: komodo
      restart: unless-stopped
      depends_on:
         - komodo-mongo
      ports:
         - ${KOMODO_PORT}:9120
      extra_hosts:
         - host.docker.internal:host-gateway
      labels:
         - 'traefik.enable=true'
         - 'traefik.http.routers.komodo.entrypoints=http'
         - 'traefik.http.routers.komodo.rule=Host(`komodo.egirldev.co.uk`) || Host(`komodo.egirl.ing`)'
         - 'traefik.http.middlewares.komodo-https-redirect.redirectscheme.scheme=https'
         - 'traefik.http.routers.komodo.middlewares=komodo-https-redirect'
         - 'traefik.http.routers.komodo-secure.entrypoints=https'
         - 'traefik.http.routers.komodo-secure.rule=Host(`komodo.egirldev.co.uk`) || Host(`komodo.egirl.ing`)'
         - 'traefik.http.routers.komodo-secure.tls=true'
         - 'traefik.http.routers.komodo-secure.tls.certresolver=cloudflare'
         - 'traefik.http.routers.komodo-secure.tls.domains[0].main=egirldev.co.uk'
         - 'traefik.http.routers.komodo-secure.tls.domains[0].sans=komodo.egirldev.co.uk'
         - 'traefik.http.routers.komodo-secure.tls.domains[1].sans=komodo.egirl.ing'
         - 'traefik.http.routers.komodo-secure.tls.domains[1].main=komodo.egirl.ing'
         - 'traefik.http.routers.komodo-secure.service=komodo'
         - 'traefik.http.services.komodo.loadbalancer.server.port=9120'
      environment: # https://github.com/mbecker20/komodo/blob/main/config_example/core.config.example.toml
         KOMODO_HOST: https://komodo.egirl.ing
         KOMODO_TITLE: Egirltainer # Change the app title, displayed in the browser tab.
         ## MONGO
         KOMODO_MONGO_ADDRESS: komodo-mongo:27017
         KOMODO_MONGO_USERNAME: ${KOMODO_MONGO_USERNAME}
         KOMODO_MONGO_PASSWORD: ${KOMODO_MONGO_PASSWORD}
         KOMODO_PASSKEY: ${KOMODO_PASSKEY}
         KOMODO_WEBHOOK_SECRET: ${KOMODO_WEBHOOK_SECRET}
         KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET}
         KOMODO_LOCAL_AUTH: true
   komodo-mongo:
      image: mongo
      command: --quiet # suppress mongo logs a bit
      restart: unless-stopped
      logging:
         driver: local
      ports:
         - 27017:27017
      volumes:
         - db-data:/data/db
         - db-config:/data/configdb
      environment:
         MONGO_INITDB_ROOT_USERNAME: ${KOMODO_MONGO_USERNAME} # change these
         MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_MONGO_PASSWORD}
   #komodo-periphery:
   #   image: ghcr.io/mbecker20/periphery:latest # use ghcr.io/mbecker20/periphery:latest-aarch64 for arm support
   #   logging:
   #      driver: local
   #   ports:
   #      - 8120:8120
   #   volumes:
   #      - /var/run/docker.sock:/var/run/docker.sock
   #      - komodo-repos:/etc/komodo/repos # manage repos in a docker volume, or change it to an accessible host directory.
   #      - komodo-stacks:/etc/komodo/stacks # manage stacks in a docker volume, or change it to an accessible host directory.
