services:
   multiscrobbler:
      image: foxxmd/multi-scrobbler:latest
      container_name: multiscrobbler
      restart: unless-stopped
      entrypoint: /init
      working_dir: /app
      volumes:
         - /opt/multiscrobbler/config:/config
      environment:
         - PUID=1000
         - PGID=1000
         - TZ=Europe/Berlin
         - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
         - HOME=/root
         - TERM=xterm
         - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
         - S6_VERBOSITY=1
         - S6_STAGE2_HOOK=/docker-mods
         - VIRTUAL_ENV=/lsiopy
         - CONFIG_DIR=/config
         - NODE_ENV=production
         - IS_DOCKER=true
         - PORT=9087
      labels:
         - 'traefik.enable=true'
         - 'traefik.http.routers.multiscrobbler.entrypoints=http'
         - 'traefik.http.routers.multiscrobbler.rule=Host(`multiscrobbler.egirl.ing`)'
         - 'traefik.http.middlewares.multiscrobbler-https-redirect.redirectscheme.scheme=https'
         - 'traefik.http.routers.multiscrobbler.middlewares=multiscrobbler-https-redirect'
         - 'traefik.http.routers.multiscrobbler-secure.entrypoints=https'
         - 'traefik.http.routers.multiscrobbler-secure.rule=Host(`multiscrobbler.egirl.ing`)'
         - 'traefik.http.routers.multiscrobbler-secure.tls=true'
         - 'traefik.http.routers.multiscrobbler-secure.tls.certresolver=cloudflare'
         - 'traefik.http.routers.multiscrobbler-secure.middlewares=authentik@file'
         - 'traefik.http.routers.multiscrobbler-secure.tls.domains[0].sans=multiscrobbler.egirl.ing'
         - 'traefik.http.routers.multiscrobbler-secure.tls.domains[0].main=egirl.ing'
         - 'traefik.http.routers.multiscrobbler-secure.service=multiscrobbler'
         - 'traefik.http.services.multiscrobbler.loadbalancer.server.port=9087'
