services:
   #miellaweb:
   #   image: miellaweb:latest
   #   container_name: miellaweb
   #   restart: unless-stopped
   #   environment:
   #      - PORT=3000
   #   labels:
   #      - 'traefik.enable=true'
   #      - 'traefik.http.routers.miellaweb.rule=Host(`egirl.ing`)'
   #      - 'traefik.http.routers.miellaweb.entrypoints=http'
   #      - 'traefik.http.routers.miellaweb.middlewares=miellaweb-https-redirect'
   #      - 'traefik.http.middlewares.miellaweb-https-redirect.redirectscheme.scheme=https'
   #      - 'traefik.http.routers.miellaweb-secure.rule=Host(`egirl.ing`)'
   #      - 'traefik.http.routers.miellaweb-secure.entrypoints=https'
   #      - 'traefik.http.routers.miellaweb-secure.tls=true'
   #      - 'traefik.http.routers.miellaweb-secure.tls.certresolver=cloudflare'
   #      - 'traefik.http.routers.miellaweb-secure.tls.domains[0].sans=egirl.ing'
   #      - 'traefik.http.routers.miellaweb-secure.tls.domains[0].main=egirl.ing'
   #      - 'traefik.http.routers.miellaweb-secure.service=miellaweb-node'
   #      - 'traefik.http.services.miellaweb-node.loadbalancer.server.port=3000'
   #   volumes:
   #      - /opt/html/miellaweb:/usr/app/public
   #      - /opt/html/server.js:/usr/app/server.js

   miellawebnew:
      image: miellawebnew:latest
      container_name: miellawebnew
      environment:
         - PORT=3000
      restart: unless-stopped
      labels:
         - 'traefik.enable=true'
         - 'traefik.http.routers.miellawebnew.rule=Host(`egirl.ing`)'
         - 'traefik.http.routers.miellawebnew.entrypoints=http'
         - 'traefik.http.routers.miellawebnew.middlewares=miellawebnew-https-redirect'
         - 'traefik.http.middlewares.miellaweb-https-redirect.redirectscheme.scheme=https'
         - 'traefik.http.routers.miellawebnew-secure.rule=Host(`egirl.ing`)'
         - 'traefik.http.routers.miellawebnew-secure.entrypoints=https'
         - 'traefik.http.routers.miellawebnew-secure.tls=true'
         - 'traefik.http.routers.miellawebnew-secure.tls.certresolver=cloudflare'
         - 'traefik.http.routers.miellawebnew-secure.tls.domains[0].sans=egirl.ing'
         - 'traefik.http.routers.miellawebnew-secure.tls.domains[0].main=egirl.ing'
         - 'traefik.http.routers.miellawebnew-secure.service=miellawebnew'
         - 'traefik.http.services.miellawebnew.loadbalancer.server.port=3000'
      volumes:
         - /opt/html/miellawebNew/league-css:/usr/app/public/league-css
         - /opt/html/miellawebNew/stuff:/usr/app/public/stuff

   ao3-tracker:
      image: ao3-tracker:latest
      container_name: ao3-tracker
      environment:
         - API_KEY=${AO3_API_KEY}
         - PORT=8092
      restart: unless-stopped
      labels:
         - 'traefik.enable=true'
         - 'traefik.http.routers.ao3-tracker.rule=Host(`ao3.egirl.ing`)'
         - 'traefik.http.routers.ao3-tracker.entrypoints=http'
         - 'traefik.http.routers.ao3-tracker.middlewares=ao3-tracker-https-redirect'
         - 'traefik.http.middlewares.ao3-tracker-https-redirect.redirectscheme.scheme=https'
         - 'traefik.http.routers.ao3-tracker-secure.rule=Host(`ao3.egirl.ing`)'
         - 'traefik.http.routers.ao3-tracker-secure.entrypoints=https'
         - 'traefik.http.routers.ao3-tracker-secure.tls=true'
         - 'traefik.http.routers.ao3-tracker-secure.tls.certresolver=cloudflare'
         - 'traefik.http.routers.ao3-tracker-secure.tls.domains[0].sans=ao3.egirl.ing'
         - 'traefik.http.routers.ao3-tracker-secure.tls.domains[0].main=ao3.egirl.ing'
         - 'traefik.http.routers.ao3-tracker-secure.service=ao3-tracker'
         - 'traefik.http.services.ao3-tracker.loadbalancer.server.port=8092'
      volumes:
         - /opt/ao3-tracker/:/data/
